from __future__ import annotations

from pathlib import Path
import json
import os
import subprocess

from .models import SubTask, Task


class AgentAdapter:
    name = "base"

    def run(self, task: Task, subtask: SubTask) -> dict[str, str]:
        raise NotImplementedError


class DemoAgentAdapter(AgentAdapter):
    name = "demo"

    def run(self, task: Task, subtask: SubTask) -> dict[str, str]:
        target = Path(task.project_root) / subtask.path
        target.parent.mkdir(parents=True, exist_ok=True)
        content = (
            f"# {subtask.path}\n\n"
            f"Generated by Across Orchestrator demo adapter.\n\n"
            f"Task: {task.goal}\n"
            f"Subtask: {subtask.goal}\n"
        )
        target.write_text(content, encoding="utf-8")
        return {"path": subtask.path, "message": "artifact written"}


class CommandAgentAdapter(AgentAdapter):
    name = "command"

    def __init__(self, command: list[str]):
        if not command:
            raise ValueError("command adapter requires a command")
        self.command = command

    def run(self, task: Task, subtask: SubTask) -> dict[str, str]:
        env = os.environ.copy()
        env["ACROSS_TASK_JSON"] = json.dumps(task.to_dict(), sort_keys=True)
        env["ACROSS_SUBTASK_JSON"] = json.dumps(subtask.__dict__, sort_keys=True)
        completed = subprocess.run(
            self.command,
            cwd=task.project_root,
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=300,
            check=False,
        )
        if completed.returncode != 0:
            raise RuntimeError(completed.stderr.strip() or completed.stdout.strip() or "command adapter failed")
        return {"path": subtask.path, "message": completed.stdout.strip()}


def adapter_for(agent: str, command: list[str] | None = None) -> AgentAdapter:
    if agent == "demo":
        return DemoAgentAdapter()
    if agent == "command":
        return CommandAgentAdapter(command or [])
    raise ValueError(f"Unknown agent adapter: {agent}")
